In [2]:
!pip install pretty-confusion-matrix
!pip install scikit-plot
!pip install matplotlib==3.1.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 73 kB 1.5 MB/s 
     |████████████████████████████████| 103 kB 53.6 MB/s 
     |████████████████████████████████| 11.2 MB 50.8 MB/s 
     |████████████████████████████████| 156 kB 51.5 MB/s 
     |████████████████████████████████| 199 kB 56.3 MB/s 
     |████████████████████████████████| 843 kB 46.9 MB/s 
     |████████████████████████████████| 68 kB 6.8 MB/s 
     |████████████████████████████████| 41 kB 634 kB/s 
     |████████████████████████████████| 965 kB 54.9 MB/s 
     |████████████████████████████████| 8.8 MB 49.3 MB/s 
     |████████████████████████████████| 98 kB 8.8 MB/s 
     |████████████████████████████████| 468 kB 59.7 MB/s 
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2344 sha256=ff64ddead002bcbf2f895d151fa2a998638277155863d37db09dfd2263c1a1ec
  Stored in directory: /root/.cache/pip/wheels/42/56/cc/4

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 13.1 MB 7.7 MB/s 
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.5.3
    Uninstalling matplotlib-3.5.3:
      Successfully uninstalled matplotlib-3.5.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pretty-confusion-matrix 0.1.1 requires matplotlib<4.0.0,>=3.5.0, but you have matplotlib 3.1.1 which is incompatible.


In [77]:
from tensorflow.keras.datasets import cifar10
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [78]:
(train_images, train_labels), (test_images, test_labels) = cifar10.load_data()

In [79]:
train_images.shape, type(train_images), train_labels.shape, type(train_labels)

((50000, 32, 32, 3), numpy.ndarray, (50000, 1), numpy.ndarray)

In [80]:
train_labels

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [81]:
train_images[12]

array([[[164, 215, 244],
        [162, 212, 240],
        [162, 212, 240],
        ...,
        [157, 210, 237],
        [153, 208, 235],
        [153, 203, 234]],

       [[168, 218, 245],
        [166, 215, 242],
        [166, 215, 242],
        ...,
        [164, 212, 238],
        [160, 209, 236],
        [158, 205, 235]],

       [[172, 220, 246],
        [170, 217, 243],
        [171, 218, 244],
        ...,
        [168, 212, 238],
        [165, 208, 235],
        [163, 207, 236]],

       ...,

       [[123, 160, 105],
        [117, 154, 102],
        [112, 149,  99],
        ...,
        [117, 136, 100],
        [ 95, 115,  79],
        [120, 149, 100]],

       [[120, 156, 100],
        [116, 151,  99],
        [112, 147,  96],
        ...,
        [126, 149, 110],
        [120, 144, 103],
        [120, 152, 101]],

       [[121, 154,  96],
        [120, 152,  99],
        [116, 148,  97],
        ...,
        [124, 152, 108],
        [124, 154, 107],
        [120, 154, 100]]

In [82]:
train_images = train_images.reshape((train_images.shape[0], train_images.shape[1] * train_images.shape[2] * train_images.shape[3])).astype("float32")/255
test_images = test_images.reshape((test_images.shape[0], test_images.shape[1] * test_images.shape[2] * test_images.shape[3])).astype("float32")/255

In [83]:
train_images

array([[0.23137255, 0.24313726, 0.24705882, ..., 0.48235294, 0.36078432,
        0.28235295],
       [0.6039216 , 0.69411767, 0.73333335, ..., 0.56078434, 0.52156866,
        0.5647059 ],
       [1.        , 1.        , 1.        , ..., 0.3137255 , 0.3372549 ,
        0.32941177],
       ...,
       [0.13725491, 0.69803923, 0.92156863, ..., 0.04705882, 0.12156863,
        0.19607843],
       [0.7411765 , 0.827451  , 0.9411765 , ..., 0.7647059 , 0.74509805,
        0.67058825],
       [0.8980392 , 0.8980392 , 0.9372549 , ..., 0.6392157 , 0.6392157 ,
        0.6313726 ]], dtype=float32)

In [84]:
split_val = 5000
train_images, val_images = train_images[split_val:], train_images[:split_val]
train_labels, val_labels = train_labels[split_val:], train_labels[:split_val]

In [85]:
train_images

array([[0.23529412, 0.32156864, 0.21176471, ..., 0.1764706 , 0.2784314 ,
        0.15686275],
       [0.88235295, 0.91764706, 0.94509804, ..., 0.16470589, 0.12156863,
        0.10980392],
       [0.99607843, 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [0.13725491, 0.69803923, 0.92156863, ..., 0.04705882, 0.12156863,
        0.19607843],
       [0.7411765 , 0.827451  , 0.9411765 , ..., 0.7647059 , 0.74509805,
        0.67058825],
       [0.8980392 , 0.8980392 , 0.9372549 , ..., 0.6392157 , 0.6392157 ,
        0.6313726 ]], dtype=float32)

In [86]:
train_labels = tf.keras.utils.to_categorical(train_labels, dtype ="uint8")
test_labels = tf.keras.utils.to_categorical(test_labels, dtype ="uint8")

In [87]:
class LogisticRegression(keras.Model):
    def train_step(self, data):
        if len(data) == 3:
            input, y, sample_weight = data
        else:
            sample_weight = None
            input, y = data

        with tf.GradientTape() as tape:
            y_pred = self(input, training=True)
            loss = self.compiled_loss(
                y,
                y_pred,
                sample_weight=sample_weight,
                regularization_losses=self.losses,
            )

        trainable_vars = self.trainable_variables
        gradients = tape.gradient(loss, trainable_vars)

        self.optimizer.apply_gradients(zip(gradients, trainable_vars))

        self.compiled_metrics.update_state(y, y_pred, sample_weight=sample_weight)

        return {m.name: m.result() for m in self.metrics}

In [88]:
train_is = train_images.shape
train_images[4]
val_labels

array([[6],
       [9],
       [9],
       ...,
       [5],
       [4],
       [6]], dtype=uint8)

In [89]:
inputs = keras.Input(shape=(32 * 32 * 3, ))
features = layers.Dense(1024, activation="relu")(inputs)
features = layers.Dropout(0.5)(features)
outputs = layers.Dense(10, activation="softmax")(features)
model = LogisticRegression(inputs, outputs)

In [93]:
model.compile(
    optimizer=keras.optimizers.RMSprop(),
    loss=keras.losses.MeanAbsoluteError(),
    metrics=[keras.metrics.MeanAbsoluteError()])


In [ ]:
model.fit(
    train_images,
    train_labels,
    epochs=10,
)

Epoch 1/10
 206/1407 [===>..........................] - ETA: 47s - loss: 0.1732 - mean_absolute_error: 0.1732